def jobsKeys():
    # return the list of keys
    return [
        "Software Engineer",
        "Data Scientist",
        "Product Manager",
        "Project Manager",
        "Business Analyst",
        "Data Analyst",
        "Financial Analyst",
        "Accountant",
        "Marketing Manager",
        "Sales Manager",
        "HR Manager",
        "Customer Service",
        "Graphic Designer",
        "UX/UI Designer",
        "Web Developer",
        "Mobile Developer",
        "Network Engineer",
        "System Administrator",
        "DevOps Engineer",
        "Cloud Engineer",
        "Security Engineer",
        "QA Engineer",
        "Technical Support",
        "Technical Writer",
        "Scrum Master",
        "Product Owner",
        "Business Development",
        "Operations Manager",
        "Supply Chain Manager",
        "Logistics Manager",
        "Warehouse Manager",
        "Quality Manager",
        "Maintenance Manager",
        "Production Manager",
        "Manufacturing Manager",
        "Construction Manager",
        "Facilities Manager",
        "Safety Manager",
        "Environmental Manager",
        "Health and Safety",
        "EHS Manager",
        "Compliance Manager",
        "Regulatory Affairs",
        "Risk Manager",
        "Audit Manager",
        "Legal Counsel",
        "Paralegal",
        "Legal Assistant",
        "Legal Secretary",
        "Legal Administrator",
        "Legal Executive",
        "Legal Advisor",
        "Legal Consultant",
        "Legal Specialist",
        "Legal Analyst",
        "Legal Coordinator"
    ]
